### ISSUE TITLE
No such file or directory: './data/processed/log.txt'

### ISSUE THREAD

**Issue by Mansoor35** [adeboissiere/FUSION-human-action-recognition#5]
Hi, I am implementing the code on my windows. 

I am stuck in this error, while running gmake_dataset file. The error I get is following. 

Traceback (most recent call last):
  File "C:/Users/mteevno2/OneDrive - City University of Hong Kong/coding/FUSION-human-action-recognition-master/FUSION-human-action-recognition-master/src/data/make_dataset.py", line 65, in <module>
    create_h5_ir_dataset(arg.data_path,
  File "C:/Users/mteevno2/OneDrive - City University of Hong Kong/coding/FUSION-human-action-recognition-master/FUSION-human-action-recognition-master\src\data\make_dataset_utils.py", line 126, in create_h5_ir_dataset
    file = open(output_folder + 'log.txt', 'w')
FileNotFoundError: [Errno 2] No such file or directory: './data/processed/log.txt'

How to solve it, kindly help.

**Comment by adeboissiere** [comment]
Hello, thanks for trying out the code! Could you figure out the issue? The log file log.txt should be created automatically when calling the make command. Perhaps try to create an empty log.txt file. I don't have any an issue on my side. Can you give me more information? 
Thanks

**Comment by Mansoor35** [comment]
Thank you.

I successfully run the code

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adeboissiere** [comment]
You're welcome! Don't hesite if you have questions. I'll close the issue.
